name: "Continuous Integration"

on:
    pull_request:
        branches:
            - "*"
            - '!analysis-*'
    push:

env:
    fail-fast: true

jobs:
    phpunit:
        name: "PHPUnit"
        runs-on: "ubuntu-20.04"

        strategy:
            matrix:
                php-version:
                    - "7.1"
                    - "7.2"
                    - "7.3"
                    - "7.4"
                    - "8.0"
                coverage:
                    - "false"
                dependencies:
                    - "highest"
                include:
                    - dependencies: "lowest"
                      php-version: "7.3"
                      coverage: "true"

        steps:
            - name: "Checkout"
              uses: "actions/checkout@v2"
              with:
                  fetch-depth: 2

            - name: "Install PHP"
              uses: "shivammathur/setup-php@v2"
              with:
                  php-version: "${{ matrix.php-version }}"
                  ini-values: "zend.assertions=1"

            - name: "Install dependencies with Composer"
              uses: "ramsey/composer-install@v1"
              with:
                  dependency-versions: "${{ matrix.dependencies }}"
                  composer-options: "--prefer-dist"

            - name: "Run Tests"
              if: matrix.coverage == 'false'
              run: "composer test"

            - name: "Run Tests with coverage"
              if: matrix.coverage == 'true'
              run: "composer test-ci"

            - name: "Download ocular"
              if: matrix.coverage == 'true'
              run: "wget https://scrutinizer-ci.com/ocular.phar"

            - name: "Upload coverage"
              if: matrix.coverage == 'true'
              run: "php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml"


